FinalPracticeMVC/Models/ErrorViewModel.cs
using System;

namespace FinalPracticeMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinalPracticeMVC/Models/Protein.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalPracticeMVC.Models
{
    public class Protein
    {
        public int ID { get; set; }
        public string Animal { get; set; }
        public string Name { get; set; }
        
        public int ServingSize { get; set; }
        public double ProteinTot { get; set; }
        public double FatTot { get; set; }
        public double Calories { get; set; }
    }
}

FinalPracticeMVC/Models/ProteinAnimalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinalPracticeMVC.Models
{
    public class ProteinAnimalViewModel
    {
        public List<Protein> Proteins { get; set; }
        public SelectList Animal {get;set;}
        public string ProteinAnimal {get;set;}
        public string SearchString { get; set; }
    }
}

FinalPracticeMVC/Controllers/HomeController.cs
using FinalPracticeMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FinalPracticeMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalPracticeMVC/Controllers/ProteinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalPracticeMVC.Data;
using FinalPracticeMVC.Models;

namespace FinalPracticeMVC.Controllers
{
    public class ProteinsController : Controller
    {
        private readonly FinalPracticeMVCContext _context;

        public ProteinsController(FinalPracticeMVCContext context)
        {
            _context = context;
        }

        // GET: Proteins
        /*
        public async Task<IActionResult> Index()
        {
            return View(await _context.Protein.ToListAsync());
        }
        */
        public async Task<IActionResult> Index(string animalProtein, string searchString) {
            IQueryable<string> animalQuery = from p in _context.Protein
                                             orderby p.Animal
                                             select p.Animal;
            var animals = from p in _context.Protein
                          select p;


        }
        // GET: Proteins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proteins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Animal,Name,ServingSize,ProteinTot,FatTot,Calories")] Protein protein)
        {
            if (ModelState.IsValid)
            {
                _context.Add(protein);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(protein);
        }

        // GET: Proteins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var protein = await _context.Protein.FindAsync(id);
            if (protein == null)
            {
                return NotFound();
            }
            return View(protein);
        }

        // POST: Proteins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Animal,Name,ServingSize,ProteinTot,FatTot,Calories")] Protein protein)
        {
            if (id != protein.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(protein);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProteinExists(protein.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(protein);
        }

        // GET: Proteins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var protein = await _context.Protein
                .FirstOrDefaultAsync(m => m.ID == id);
            if (protein == null)
            {
                return NotFound();
            }

            return View(protein);
        }

        // POST: Proteins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var protein = await _context.Protein.FindAsync(id);
            _context.Protein.Remove(protein);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProteinExists(int id)
        {
            return _context.Protein.Any(e => e.ID == id);
        }
    }
}

FinalPracticeMVC/Views/Proteins/Create.cshtml
@model FinalPracticeMVC.Models.Protein

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Protein</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Animal" class="control-label"></label>
                <input asp-for="Animal" class="form-control" />
                <span asp-validation-for="Animal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServingSize" class="control-label"></label>
                <input asp-for="ServingSize" class="form-control" />
                <span asp-validation-for="ServingSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProteinTot" class="control-label"></label>
                <input asp-for="ProteinTot" class="form-control" />
                <span asp-validation-for="ProteinTot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FatTot" class="control-label"></label>
                <input asp-for="FatTot" class="form-control" />
                <span asp-validation-for="FatTot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalPracticeMVC/Views/Proteins/Delete.cshtml
@model FinalPracticeMVC.Models.Protein

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Protein</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Animal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Animal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServingSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServingSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProteinTot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProteinTot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatTot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatTot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calories)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalPracticeMVC/Views/Proteins/Details.cshtml
@model FinalPracticeMVC.Models.Protein

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Protein</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Animal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Animal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServingSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServingSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProteinTot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProteinTot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatTot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatTot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calories)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FinalPracticeMVC/Views/Proteins/Edit.cshtml
@model FinalPracticeMVC.Models.Protein

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Protein</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Animal" class="control-label"></label>
                <input asp-for="Animal" class="form-control" />
                <span asp-validation-for="Animal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServingSize" class="control-label"></label>
                <input asp-for="ServingSize" class="form-control" />
                <span asp-validation-for="ServingSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProteinTot" class="control-label"></label>
                <input asp-for="ProteinTot" class="form-control" />
                <span asp-validation-for="ProteinTot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FatTot" class="control-label"></label>
                <input asp-for="FatTot" class="form-control" />
                <span asp-validation-for="FatTot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalPracticeMVC/Views/Proteins/Index.cshtml
@model FinalPracticeMVC.Models.ProteinAnimalViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Proteins" asp-action="Index" method="get">

    <p>
        <select asp-for="Animal" asp-items="Model.Animal">
            <option value="">
                All
            </option>
        </select>
        Title:<input type="text" name="SearchString" asp-for="SearchString"/>
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Proteins[0].Animal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proteins[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proteins[0].ServingSize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proteins[0].ProteinTot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proteins[0].FatTot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proteins[0].Calories)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Proteins)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Animal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ServingSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProteinTot)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FatTot)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Calories)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

FinalPracticeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalPracticeMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalPracticeMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proteins" asp-action="Index">Protein</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FinalPracticeMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>